name: goreleaser

on:
  push:

jobs:
  goreleaser:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Build fordirection (fordirection)
        uses: crazy-max/ghaction-xgo@v1
        with:
          dest: build
          pkg: fordirection/cmd/fordirection
          prefix: fordirection
          targets: windows/386,windows/amd64,linux/386,linux/amd64,darwin/386,darwin/amd64
          v: true
          x: true
      - name: Build fordirection (fordirection-golangci-lint)
        uses: crazy-max/ghaction-xgo@v1
        with:
          dest: build
          pkg: fordirection/plugin
          prefix: fordirection-golangci-lint
          targets: windows/386,windows/amd64,linux/386,linux/amd64,darwin/386,darwin/amd64
          v: true
          x: true
          buildmode: plugin
